AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
